# Generated by Django 4.1.1 on 2022-11-24 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 11, 59, 41, 730627, tzinfo=datetime.timezone.utc), verbose_name='activity end date'),
        ),
    ]
