# Generated by Django 4.1.1 on 2022-11-24 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='activity end date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.IntegerField(),
        ),
    ]
